# Generated by Django 5.0.6 on 2024-07-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BalansToldirish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summa', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BalansYechish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('summa', models.PositiveIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='GetRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('getrequest_type', models.CharField(choices=[('yolovchi_olish', 'Yolovchi olish'), ('pochta_olish', 'Pochta olish')], default='yolovchi_olish', max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('request_type', models.CharField(choices=[('yolovchi_berish', 'Yolovchi berish'), ('pochta_berish', 'Pochta berish')], default='passenger_issue', max_length=20)),
                ('where', models.CharField(choices=[('toshkent', 'Toshkent'), ("bog'dod-rishton-buvayda", "Bog'dod-Rishton-Buvayda"), ("qo'qon", "Qo'qon"), ("uchko'prik", "Uchko'prik")], default='toshkent', max_length=100)),
                ('whereTo', models.CharField(choices=[('toshkent', 'Toshkent'), ("bog'dod-rishton-buvayda", "Bog'dod-Rishton-Buvayda"), ("qo'qon", "Qo'qon"), ("uchko'prik", "Uchko'prik")], default='toshkent', max_length=100)),
                ('yolovchiSoni', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='1', max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('is_active', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
