# Generated by Django 5.0.6 on 2024-11-29 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxi', '0004_advertisement'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
